{"name": "test_enterDataInEditBox", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <AppiumFramework.pages.LoginPage.LoginPageTest object at 0x0000021143F4AF70>, text = 'Code2Lead', locatorValue = 'com.code2lead.kwad:id/Edt_admin', locatorType = 'id'\n\n    def sendText(self, text, locatorValue, locatorType=\"id\"):\n        element = None\n        try:\n            locatorType = locatorType.lower()\n            element = self.getElement(locatorValue, locatorType)\n>           element.send_keys(text)\nE           AttributeError: 'NoneType' object has no attribute 'send_keys'\n\n..\\base\\BasePage.py:76: AttributeError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <AppiumFramework.tests.LoginTest.LoginTest testMethod=test_enterDataInEditBox>\n\n    @pytest.mark.run(order=5)\n    def test_enterDataInEditBox(self):\n>       self.gt.enterText()\n\nLoginTest.py:18: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\pages\\LoginPage.py:48: in enterText\n    self.sendText(\"Code2Lead\",self._enterText,\"id\")\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <AppiumFramework.pages.LoginPage.LoginPageTest object at 0x0000021143F4AF70>, text = 'Code2Lead', locatorValue = 'com.code2lead.kwad:id/Edt_admin', locatorType = 'id'\n\n    def sendText(self, text, locatorValue, locatorType=\"id\"):\n        element = None\n        try:\n            locatorType = locatorType.lower()\n            element = self.getElement(locatorValue, locatorType)\n            element.send_keys(text)\n            self.log.info(\n                \"Send text  on Element with LocatorType: \" + locatorType + \" and with the locatorValue :\" + locatorValue)\n        except:\n            self.log.info(\n                \"Unable to send text on Element with LocatorType: \" + locatorType + \" and with the locatorValue :\" + locatorValue)\n            self.takeScreenshot(locatorType)\n>           assert False\nE           AssertionError\n\n..\\base\\BasePage.py:83: AssertionError"}, "attachments": [{"name": "id", "source": "349b17e8-6cae-447e-8272-62e8b0d247e5-attachment.png", "type": "image/png"}, {"name": "log", "source": "9d6094d6-6533-4c7e-9d90-53266cb09052-attachment.txt", "type": "text/plain"}], "start": 1673309598598, "stop": 1673309624617, "uuid": "dfe3bf42-7c15-43ba-8811-ff0d587947d9", "historyId": "6c6221cbf91eb27c548322f4fd168190", "testCaseId": "cccab356436a367c95d20d864482b967", "fullName": "LoginTest.LoginTest#test_enterDataInEditBox", "labels": [{"name": "tag", "value": "run(order=5)"}, {"name": "tag", "value": "@pytest.mark.usefixtures('beforeClass', 'beforeMethod')"}, {"name": "suite", "value": "LoginTest"}, {"name": "subSuite", "value": "LoginTest"}, {"name": "host", "value": "DESKTOP-CL62PMK"}, {"name": "thread", "value": "9160-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "LoginTest"}]}